### PR TITLE
Add JWS reference trajectories

### PR DESCRIPTION
**Pull request by yannikschaelte**

### CODE REVIEW

**Review by paulstapor — CHANGES_REQUESTED** [review]
If we already set things up new and clean: Let's please remove the json iles.

**Comment by yannikschaelte** [comment]
> If we already set things up new and clean: Let's please remove the json iles.

True ... thought I had removed them already.

**Comment by yannikschaelte** [comment]
Should be removed now. Please only squash and merge, to keep those json out of the history.

**Review by paulstapor — APPROVED** [review]
:+1:

**Pull request merged**
